import sys
import os
import httpx

sys.path.append(os.path.abspath(os.path.dirname(__file__)))

BASE_URL = "http://127.0.0.1:8001/api/v1"

def print_result(step: int, description: str, passed: bool, error_msg: str = ""):
    status = "[OK]" if passed else "[ERROR]"
    msg = f" {error_msg}" if error_msg else ""
    print(f"  {step}. {status} {description}{msg}")
    if not passed:
        sys.exit(1)

def run_tests():
    print("=== Verify Notification & Reminder Engine ===")
    client = httpx.Client()
    
    email = "notifications.test@finrelief.ai"
    password = "password123"
    
    # 1. Clean up user
    db = None
    try:
        from app.database.session import SessionLocal
        from app.models.user import User
        db = SessionLocal()
        u = db.query(User).filter(User.email == email).first()
        if u:
            db.delete(u)
            db.commit()
    except Exception as e:
        print(f"Error cleaning user: {e}")
    finally:
        if db:
            db.close()

    # 2. Register & Login
    r = client.post(f"{BASE_URL}/auth/register", json={
        "name": "Notification Test User",
        "email": email,
        "password": password,
        "monthly_income": 4000.0,
        "monthly_expenses": 2000.0
    })
    if r.status_code != 201:
        print_result(1, "Register Test User", False, f"HTTP {r.status_code}: {r.text}")
    
    r = client.post(f"{BASE_URL}/auth/login", json={"email": email, "password": password})
    if r.status_code != 200:
        print_result(2, "Login Test User", False, f"HTTP {r.status_code}: {r.text}")
    
    token = r.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}
    print_result(2, "Authenticated user", True)

    # 3. Create dummy loans
    r = client.post(f"{BASE_URL}/loans", json={
        "lender_name": "Chase Bank", "loan_type": "Personal", "outstanding_amount": 10000.0, "interest_rate": 8.5, "emi": 500.0, "overdue_months": 0
    }, headers=headers)
    if r.status_code != 201:
        print_result(3, "Create active loan", False, r.text)

    r = client.post(f"{BASE_URL}/loans", json={
        "lender_name": "Wells Fargo", "loan_type": "Auto", "outstanding_amount": 20000.0, "interest_rate": 6.2, "emi": 400.0, "overdue_months": 4
    }, headers=headers)
    if r.status_code != 201:
        print_result(3, "Create overdue loan", False, r.text)
    
    print_result(3, "Liability setup completed", True)

    # 4. Trigger scheduler jobs manually
    print("  4. Running scheduler routines manually...")
    try:
        from app.services.scheduler_service import (
            check_upcoming_emis,
            check_overdue_payments,
            check_settlement_options,
            send_weekly_summaries
        )
        
        check_overdue_payments()
        check_settlement_options()
        send_weekly_summaries()
        print_result(4, "Scheduler routines executed", True)
    except Exception as e:
        print_result(4, "Execute scheduler routines", False, str(e))

    # 5. Fetch notifications via API
    r = client.get(f"{BASE_URL}/notifications", headers=headers)
    if r.status_code != 200:
        print_result(5, "Fetch notifications", False, f"HTTP {r.status_code}")
    
    notifications = r.json()["data"]
    if len(notifications) == 0:
        print_result(5, "Validate notifications list", False, "No notifications generated by scheduler routines.")
    
    first_notif = notifications[0]
    notif_id = first_notif["id"]
    print_result(5, f"Retrieved {len(notifications)} notifications successfully", True)

    # 6. Mark notification as read
    r = client.put(f"{BASE_URL}/notifications/{notif_id}/read", headers=headers)
    if r.status_code != 200:
        print_result(6, "Mark notification as read", False, f"HTTP {r.status_code}")
    
    updated_notif = r.json()["data"]
    if not updated_notif["is_read"]:
        print_result(6, "Verify notification marked as read", False, "is_read is still False")
        
    print_result(6, "Notification read status updated successfully", True)

if __name__ == "__main__":
    run_tests()
