# Application Role Mappings
ROLE_ADMIN = "admin"
ROLE_USER = "user"

# Financial Baseline Limits (Placeholder values for validation bounds)
MIN_DEBT_AMOUNT = 0.0
MAX_DEBT_AMOUNT = 10_000_000.0  # $10 million threshold limit
MIN_DTI_RATIO = 0.0
MAX_DTI_RATIO = 100.0

# System Standardized API Error Codes
ERR_ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
ERR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERR_UNAUTHORIZED_ACCESS = "UNAUTHORIZED"
ERR_FORBIDDEN_ACCESS = "FORBIDDEN"
ERR_DATABASE_ERROR = "DATABASE_ERROR"
ERR_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
