from pydantic import BaseModel, Field, ConfigDict
from typing import Optional
from datetime import datetime

class NegotiationRequest(BaseModel):
    """
    Request parameters for generating negotiation guides or correspondence templates.
    """
    loan_id: int = Field(..., description="Target Loan ID to evaluate")
    custom_hardship_description: Optional[str] = Field(None, max_length=1000, description="Optional custom borrower hardship details")

class NegotiationResponse(BaseModel):
    """
    Response detailing the computed negotiation strategy layout.
    """
    loan_id: int
    strategy: str = Field(..., description="Professional negotiation strategy steps and expected creditor concerns")

class SettlementLetterResponse(BaseModel):
    """
    Response detailing the generated settlement proposal letter.
    """
    loan_id: int
    letter_content: str = Field(..., description="Generated formal proposal letter text in business layout")

class NegotiationEmailResponse(BaseModel):
    """
    Response detailing the generated email proposal message.
    """
    loan_id: int
    subject: str = Field(..., description="Subject line of the email")
    email_body: str = Field(..., description="Concise email proposal body")

class FinancialExplanationResponse(BaseModel):
    """
    Response detailing the generated plain-English metrics report interpretation.
    """
    explanation: str = Field(..., description="Plain-English explanation of metrics, risk score, and budget guides")

class AIHistoryResponse(BaseModel):
    """
    Schema representing stored AI generation logs history.
    """
    id: int
    user_id: int
    loan_id: Optional[int] = None
    prompt_type: str = Field(..., description="Category of prompt: negotiation_strategy, settlement_letter, negotiation_email, financial_explanation")
    prompt: str = Field(..., description="Input prompt text submitted to the client")
    response: str = Field(..., description="Text response content generated by the engine")
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)
